#!/usr/bin/env node

/**
 * Static post page generator
 *
 * Runs after webpack build to generate static HTML for each blog post.
 * This improves SEO by serving pre-rendered content to crawlers.
 */

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

const rootDir = path.resolve(__dirname, '..');
const publicDir = path.join(rootDir, 'public');
const contentDir = path.join(rootDir, 'content', 'blog');

// Load posts from the single source of truth
const postsData = JSON.parse(
  fs.readFileSync(path.join(rootDir, 'src', 'blog', 'posts.json'), 'utf-8')
);

// Default author
const DEFAULT_AUTHOR = {
  name: "Lasse Nordahl",
  url: "https://x.com/lassenordahl"
};

// Add author to posts
const posts = postsData.map(post => ({
  ...post,
  author: post.hasAuthor === false ? undefined : DEFAULT_AUTHOR
}));

function formatDate(dateString) {
  const [year, month, day] = dateString.split('-').map(Number);
  const date = new Date(year, month - 1, day);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric"
  });
}

function loadMarkdown(slug) {
  const filePath = path.join(contentDir, `${slug}.md`);
  try {
    const text = fs.readFileSync(filePath, 'utf-8');
    // Strip frontmatter if present
    const contentMatch = text.match(/^---[\s\S]*?---\s*([\s\S]*)$/);
    return contentMatch ? contentMatch[1].trim() : text.trim();
  } catch (err) {
    // No markdown file - might be an external link post
    return '';
  }
}

function generatePostHtml(post, baseHtml) {
  const content = loadMarkdown(post.slug);
  const htmlContent = content ? marked.parse(content) : '';

  // Generate the post detail HTML
  const postDetailHtml = `
    <div class="post-detail-content">
      <a href="/" class="back-link">&larr; Back</a>

      ${post.thumbnail ? `
        <div class="post-detail-thumbnail-container">
          <img src="${post.thumbnail}" alt="" class="post-detail-thumbnail-glow" aria-hidden="true" />
          <img src="${post.thumbnail}" alt="${post.title}" class="post-detail-thumbnail" />
        </div>
      ` : ""}

      <h1 class="post-detail-title">${post.title}</h1>
      ${post.author ? `
        <div class="post-author">
          <a href="${post.author.url}" target="_blank" rel="noopener noreferrer">${post.author.name}</a> on ${formatDate(post.date)}
        </div>
      ` : `
        <span class="post-detail-date">${formatDate(post.date)}</span>
      `}

      ${post.originalUrl ? `
        <a href="${post.originalUrl}" target="_blank" rel="noopener noreferrer" class="post-original-link">
          View Original &rarr;
        </a>
      ` : ""}

      <div class="post-divider"></div>

      <div class="post-content">
        ${htmlContent}
      </div>
    </div>
  `;

  let html = baseHtml;

  // Update the title
  html = html.replace(
    /<title>.*?<\/title>/,
    `<title>${post.title} - lasse's website</title>`
  );

  // Add Open Graph meta tags after the title
  const ogTags = `
    <meta property="og:title" content="${post.title}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://lassenordahl.com/post/${post.slug}" />
    ${post.thumbnail ? `<meta property="og:image" content="https://lassenordahl.com${post.thumbnail}" />` : ''}
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${post.title}" />
    ${post.thumbnail ? `<meta name="twitter:image" content="https://lassenordahl.com${post.thumbnail}" />` : ''}
  `;
  html = html.replace('</title>', `</title>${ogTags}`);

  // Add is-post-page class to html element
  html = html.replace('<html lang="en">', '<html lang="en" class="is-post-page">');

  // Insert pre-rendered content into post-detail div
  html = html.replace(
    /<div id="post-detail" class="post-detail"><\/div>/,
    `<div id="post-detail" class="post-detail">${postDetailHtml}</div>`
  );

  return html;
}

function main() {
  console.log('Generating static post pages...');

  // Read the base HTML template (generated by webpack)
  const baseHtmlPath = path.join(publicDir, 'index.html');
  if (!fs.existsSync(baseHtmlPath)) {
    console.error('Error: public/index.html not found. Run webpack build first.');
    process.exit(1);
  }
  const baseHtml = fs.readFileSync(baseHtmlPath, 'utf-8');

  // Generate a page for each post
  for (const post of posts) {
    const postDir = path.join(publicDir, 'post', post.slug);
    fs.mkdirSync(postDir, { recursive: true });

    const postHtml = generatePostHtml(post, baseHtml);
    const outputPath = path.join(postDir, 'index.html');
    fs.writeFileSync(outputPath, postHtml);

    console.log(`  Generated: /post/${post.slug}/index.html`);
  }

  console.log(`Done! Generated ${posts.length} post pages.`);
}

main();
